"""Create questions table

Revision ID: 001_create_questions
Revises:
Create Date: 2025-01-XX XX:XX:XX.XXXXXX

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "001_create_questions"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "questions",
        sa.Column("token", sa.String(length=255), nullable=False),
        sa.Column("group_id", sa.BIGINT(), nullable=False),
        sa.Column("topic_id", sa.Integer(), nullable=False),
        sa.Column("topic_duty_fullname", sa.Unicode(), nullable=True),
        sa.Column("employee_fullname", sa.Unicode(), nullable=False),
        sa.Column("employee_chat_id", sa.BIGINT(), nullable=False),
        sa.Column("employee_division", sa.Unicode(), nullable=True),
        sa.Column("question_text", sa.Unicode(), nullable=True),
        sa.Column("start_time", sa.DateTime(), nullable=True),
        sa.Column("end_time", sa.DateTime(), nullable=True),
        sa.Column("clever_link", sa.Unicode(), nullable=True),
        sa.Column("quality_employee", sa.Boolean(), nullable=True),
        sa.Column("quality_duty", sa.Boolean(), nullable=True),
        sa.Column("status", sa.Unicode(), nullable=True),
        sa.Column("allow_return", sa.Boolean(), nullable=False, default=True),
        sa.Column("activity_status_enabled", sa.Boolean(), nullable=True, default=None),
        sa.PrimaryKeyConstraint("token"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("questions")
    # ### end Alembic commands ###
