"""Create messages_pairs table

Revision ID: 002_create_messages_pairs
Revises: 001_create_questions
Create Date: 2025-01-XX XX:XX:XX.XXXXXX

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "002_create_messages_pairs"
down_revision: Union[str, None] = "001_create_questions"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "messages_pairs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_chat_id", sa.BigInteger(), nullable=False),
        sa.Column("user_message_id", sa.BigInteger(), nullable=False),
        sa.Column("topic_chat_id", sa.BigInteger(), nullable=False),
        sa.Column("topic_message_id", sa.BigInteger(), nullable=False),
        sa.Column("topic_thread_id", sa.BigInteger(), nullable=True),
        sa.Column("question_token", sa.String(length=255), nullable=False),
        sa.Column("direction", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), nullable=False, server_default=sa.func.now()
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    # Create indexes for better performance
    op.create_index(
        "ix_messages_pairs_user_chat_message",
        "messages_pairs",
        ["user_chat_id", "user_message_id"],
    )
    op.create_index(
        "ix_messages_pairs_topic_chat_message",
        "messages_pairs",
        ["topic_chat_id", "topic_message_id"],
    )
    op.create_index(
        "ix_messages_pairs_question_token", "messages_pairs", ["question_token"]
    )
    op.create_index("ix_messages_pairs_created_at", "messages_pairs", ["created_at"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_messages_pairs_created_at", table_name="messages_pairs")
    op.drop_index("ix_messages_pairs_question_token", table_name="messages_pairs")
    op.drop_index("ix_messages_pairs_topic_chat_message", table_name="messages_pairs")
    op.drop_index("ix_messages_pairs_user_chat_message", table_name="messages_pairs")
    op.drop_table("messages_pairs")
    # ### end Alembic commands ###
